In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('plant_growth_data.csv')
df.head()

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
0,loam,5.192294,bi-weekly,chemical,31.719602,61.591861,0
1,sandy,4.033133,weekly,organic,28.919484,52.422276,1
2,loam,8.892769,bi-weekly,none,23.179059,44.660539,0
3,loam,8.241144,bi-weekly,none,18.465886,46.433227,0
4,sandy,8.374043,bi-weekly,organic,18.128741,63.625923,0

In [3]:
df = pd.get_dummies(df, ['Soil_Type', 'Water_Frequency', 'Fertilizer_Type'])
df['Growth_Milestone'] = df.pop('Growth_Milestone')

df.head()

,Sunlight_Hours,Temperature,Humidity,Soil_Type_clay,Soil_Type_loam,Soil_Type_sandy,Water_Frequency_bi-weekly,Water_Frequency_daily,Water_Frequency_weekly,Fertilizer_Type_chemical,Fertilizer_Type_none,Fertilizer_Type_organic,Growth_Milestone
0,5.192294,31.719602,61.591861,False,True,False,True,False,False,True,False,False,0
1,4.033133,28.919484,52.422276,False,False,True,False,False,True,False,False,True,1
2,8.892769,23.179059,44.660539,False,True,False,True,False,False,False,True,False,0
3,8.241144,18.465886,46.433227,False,True,False,True,False,False,False,True,False,0
4,8.374043,18.128741,63.625923,False,False,True,True,False,False,False,False,True,0

In [4]:
df.shape

(193, 13)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = df.iloc[:, :12]
Y = df.iloc[:, 12]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=101)

rfc = RandomForestClassifier(random_state=101)
rfc.fit(X_train, Y_train)

Y_pred_train = rfc.predict(X_train)
Y_pred_test = rfc.predict(X_test)

accuracy_train = accuracy_score(Y_train, Y_pred_train)
accuracy_test = accuracy_score(Y_test, Y_pred_test)

print('Training Accuracy : ', accuracy_train)
print('Testing Accuracy : ', accuracy_test)

print('\nClassification Report :-\n', classification_report(Y_test, Y_pred_test))
print('\nConfusion Matrix :-\n', confusion_matrix(Y_test, Y_pred_test))

Training Accuracy :  1.0
Testing Accuracy :  0.625

Classification Report :-
               precision    recall  f1-score   support

           0       0.59      0.67      0.62        30
           1       0.67      0.59      0.62        34

    accuracy                           0.62        64
   macro avg       0.63      0.63      0.62        64
weighted avg       0.63      0.62      0.62        64


Confusion Matrix :-
 [[20 10]
 [14 20]]